### ISSUE TITLE
Various improvements here!

### ISSUE THREAD

**Issue by XVincentX** [brutski/snowcrash-dot-net-wrapper#5]
Hello!
I'm working on a .NET project where your .NET binding to snowcrash may be very
useful. However I encountered many _troubles_ to integrate your code into my
project.

For this reason, I have [forked](https://github.com/XVincentX/snowcrash-dot-net-wrapper) your repository and made some modifications to it.

The "list" of what I have done and what I'm going to do is here:
- [x] Change the submodule to use public repository URL
- [x] Update the wrapper to the latest snowcrash version
- [x] Change configuration for Release version of DLL (it does not compile, actually)
- [x] Make it compile on AppVeyorn  [![Build status](https://ci.appveyor.com/api/projects/status/3d0a3hebo6u2jo1w)](https://ci.appveyor.com/project/XVincentX/snowcrash-dot-net-wrapper)
- [ ] Find a way to make it AnyCPU compatible (side by side assembly loading, I think)
- [x] Create a [nuget package](https://www.nuget.org/packages/Snowcrash.NET/) and autopush on it (**x86** only for now)
- [ ] Can we do something to support Mono and Unix as well?
- [ ] Remove various warnings due to some deprecated collections ( @zdne may help there )
- [x] Run a code analisys on the entire project (removed disposable warnings)
- [ ] Full managed implementation ?!

Once that, I was tempted to make a pull request. However since I am a huge fan
of [don't push your pull request](https://www.igvita.com/2011/12/19/dont-push-your-pull-requests/)
but I really needed anyway these code changes, I decided that the best way was
open an issue and discuss together about next steps.

What do you think about this?

**V.Chianese**

**Comment by brutski** [comment]
@XVincentX Thats a good stuff. Thanks! 

I will see what can be done with regard to Mono and Unix support.

**Comment by XVincentX** [comment]
Mono-Unix support can be done only creating a full managed implementation. That what I am going to build when I will have a bit of free time.
Have fun!
